name: Compile TS and then Bundle with Webpack

on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build Plugin
      run: |
        npm install
        npx webpack
