name: Create a Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build Plugin
      run: |
        npm install
        npx webpack

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: build/attractors.js
